name: neural-sentinel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - notebook
  - pip:
    - tensorflow>=2.13.0
    - torch>=2.0.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - imbalanced-learn>=0.11.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - plotly>=5.14.0
    - web3>=6.0.0
    - ipykernel
    - jupyter-contrib-nbextensions